
[slayer]

	[slayer.sayer]
		boss_slain_timer = false

[kuudra]

	[kuudra.kuudra]
		crates_waypoints = false
		fatal_tempo_display = false

[dungeons]

	[dungeons.dungeons]
		box_star_mobs = false
		croesus_profit_mode = 0
		show_extra_stats = false
		croesus_profit = false
		chest_profit = false
		secrets_click_color = "255,0,255,0"
		boss_splits = false
		croesus_clicks_mode = 0
		run_splits = false
		show_secrets_clicked = false
		show_croesus_clicks = false

[fishing]

	[fishing.fishing]
		boss_bar = false
		rgb_timer_title = false
		timer_title = false

[tracker]

	[tracker.tracker]
		ghost_tracker = false
		powder_mining_tracker = false
		trophy_fishing_tracker = false

[garden]

	[garden.garden]
		visitor_profit_display = false

[mining]

	[mining.mining]
		emisarry_waypoints = false
		gemstone_mining_profit = false

[misc]

	[misc.misc]
		rngmeter = false
		ragnarok_axe_cooldown_timer = false

